using System.Globalization;

namespace OSCControl.DesktopHost;

internal static class DesktopLocalization
{
    private static readonly IReadOnlyDictionary<string, string> SimplifiedChinese = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["OSCControl Desktop Host"] = "OSCControl 桌面宿主",
        ["Script"] = "脚本",
        ["Open"] = "打开",
        ["Reload"] = "重新加载",
        ["Save"] = "保存",
        ["Check"] = "检查",
        ["Start"] = "启动",
        ["Stop"] = "停止",
        ["Blocks"] = "积木",
        ["Diagnostics"] = "诊断",
        ["Severity"] = "严重级别",
        ["Line"] = "行",
        ["Column"] = "列",
        ["Message"] = "消息",
        ["Runtime"] = "运行时",
        ["Idle"] = "空闲",
        ["WebSocket Client"] = "WebSocket 客户端",
        ["WebSocket Server"] = "WebSocket 服务端",
        ["Input"] = "输入",
        ["Output"] = "输出",
        ["Startup"] = "启动",
        ["Receive"] = "接收",
        ["VRChat Avatar Change"] = "VRChat 模型切换",
        ["VRChat Param"] = "VRChat 参数",
        ["Log"] = "日志",
        ["Store"] = "存储",
        ["Send"] = "发送",
        ["While"] = "循环",
        ["Break"] = "跳出循环",
        ["Continue"] = "继续下一轮",
        ["VRChat Input"] = "VRChat 输入",
        ["VRChat Chatbox"] = "VRChat 聊天框",
        ["VRChat Typing"] = "VRChat 正在输入",
        ["None"] = "无",
        ["Blocks is a one-way visual generator for now. Build endpoints, triggers, and steps here, then apply the generated script to the Script tab when you want to save or fine-tune it."] = "目前积木页还是单向生成器。你可以在这里搭建端点、触发器和步骤，然后把生成的脚本应用到脚本页，再继续保存或微调。",
        ["Add Endpoint"] = "添加端点",
        ["Add VRChat Endpoint"] = "添加 VRChat 端点",
        ["Remove Endpoint"] = "删除端点",
        ["Import Script To Blocks"] = "导入脚本到积木",
        ["Preview Script"] = "预览脚本",
        ["Apply To Script"] = "应用到脚本",
        ["Endpoints"] = "端点",
        ["Name"] = "名称",
        ["Transport"] = "传输",
        ["Mode"] = "模式",
        ["Host"] = "主机",
        ["Port"] = "端口",
        ["Input Port"] = "输入端口",
        ["Path"] = "路径",
        ["Codec"] = "编码",
        ["Rules"] = "规则",
        ["Add Startup"] = "添加启动规则",
        ["Add Receive"] = "添加接收规则",
        ["Add Avatar Change"] = "添加模型切换",
        ["Add Param Trigger"] = "添加参数触发",
        ["Move Up"] = "上移",
        ["Move Down"] = "下移",
        ["Duplicate"] = "复制",
        ["Delete"] = "删除",
        ["Rules are the block equivalent of event stacks. Drag the splitter if you want more room for this panel."] = "规则相当于事件堆栈。如果这里空间不够，可以直接拖动分隔条。",
        ["Selected Rule"] = "当前规则",
        ["Trigger"] = "触发器",
        ["Endpoint"] = "端点",
        ["Address"] = "地址",
        ["When"] = "条件",
        ["Steps"] = "步骤",
        ["Stack"] = "步骤栈",
        ["Selected Step"] = "当前步骤",
        ["Step"] = "步骤",
        ["Target"] = "目标",
        ["Value"] = "值",
        ["Payload"] = "负载",
        ["Extra"] = "附加",
        ["Add Log"] = "添加日志",
        ["Add Store"] = "添加存储",
        ["Add Send"] = "添加发送",
        ["Add While"] = "添加循环",
        ["Add Break"] = "添加跳出",
        ["Add Continue"] = "添加继续",
        ["Add Stop"] = "添加停止",
        ["Add VRChat Param"] = "添加 VRChat 参数",
        ["Add VRChat Input"] = "添加 VRChat 输入",
        ["Add VRChat Chat"] = "添加 VRChat 聊天",
        ["Add VRChat Typing"] = "添加 VRChat 输入状态",
        ["Enter Body"] = "进入循环体",
        ["Back"] = "返回上一层",
        ["Generated Script Preview"] = "生成脚本预览",
        ["Loaded script into Script tab. Blocks draft was left unchanged."] = "已将脚本加载到脚本页。积木草稿未改动。",
        ["Select a script file first"] = "请先选择脚本文件",
        ["Reloaded script into Script tab. Blocks draft was left unchanged."] = "已将脚本重新加载到脚本页。积木草稿未改动。",
        ["Saved"] = "已保存",
        ["Diagnostics found"] = "发现诊断信息",
        ["Ready"] = "就绪",
        ["Compile failed"] = "编译失败",
        ["Runtime start failed"] = "运行时启动失败",
        ["Start failed"] = "启动失败",
        ["Runtime stopped."] = "运行时已停止。",
        ["Info"] = "信息",
        ["No diagnostics."] = "没有诊断信息。",
        ["VRChat endpoint already exists."] = "已经存在 VRChat 端点。",
        ["Applied generated script to the Script tab."] = "已将生成脚本应用到脚本页。",
        ["Fix script diagnostics before importing into Blocks."] = "导入到积木前请先修复脚本诊断问题。",
        ["Imported script into Blocks."] = "已将脚本导入到积木。",
        ["Block import notes:"] = "积木导入说明：",
        ["When app starts"] = "当应用启动时",
        ["When VRChat avatar changes"] = "当 VRChat 模型切换时",
        ["Rule"] = "规则",
        ["No filter"] = "无过滤条件",
        ["Listening to /avatar/change"] = "监听 /avatar/change",
        ["Listening to /avatar/parameters/..."] = "监听 /avatar/parameters/...",
        ["No steps yet"] = "还没有步骤",
        ["Stop chain"] = "停止链",
        ["message"] = "消息",
        ["expression"] = "表达式",
        ["payload"] = "负载",
        ["Exit the current loop immediately"] = "立刻跳出当前循环",
        ["Skip to the next loop iteration"] = "跳到当前循环的下一轮",
        ["End current rule chain immediately"] = "立即结束当前规则链",
        ["chat text"] = "聊天文本",
        ["Select a step to edit it. Send steps use Target = endpoint, Value = address, Payload = args/body, Extra = payload content. While steps use Value = condition, then Enter Body to edit child steps."] = "选择一个步骤后即可编辑。发送步骤使用 目标=端点，值=地址，负载=args/body，附加=负载内容。循环步骤用 值=条件，再通过“进入循环体”编辑子步骤。",
        ["Log: Target = log level (info/warn/error/debug), Value = text or expression."] = "日志：目标 = 日志级别（info/warn/error/debug），值 = 文本或表达式。",
        ["Store: Target = state name, Value = expression to keep between events."] = "存储：目标 = 状态名，值 = 事件之间需要保留的表达式。",
        ["Send: Target = endpoint name, Value = address, Payload = Args or Body, Extra = payload content. For args you can type 1, 2, 3 and the generator will wrap it into [[...]]."] = "发送：目标 = 端点名，值 = 地址，负载 = Args 或 Body，附加 = 负载内容。对于 args，你可以直接输入 1, 2, 3，生成器会自动包成 [[...]]。",
        ["While: Value = condition expression, for example state(\"count\") < 3. Select it and click Enter Body to edit child steps."] = "循环：值 = 条件表达式，例如 state(\"count\") < 3。选中后点“进入循环体”来编辑子步骤。",
        ["Break: exits the current while immediately. Other fields are ignored."] = "跳出循环：立即结束当前 while。其他字段会被忽略。",
        ["Continue: skips the rest of the current loop iteration. Other fields are ignored."] = "继续下一轮：跳过当前循环余下步骤，进入下一轮。其他字段会被忽略。",
        ["Stop: ends the current rule chain immediately. Other fields are ignored."] = "停止：立即结束当前规则链。其他字段会被忽略。",
        ["VRChat Param: Target = avatar parameter name, Value = value to write. Generates vrchat.param."] = "VRChat 参数：目标 = Avatar 参数名，值 = 要写入的值。会生成 vrchat.param。",
        ["VRChat Input: Target = input name such as Jump / Vertical, Value = value to send."] = "VRChat 输入：目标 = 输入名，例如 Jump / Vertical，值 = 要发送的值。",
        ["VRChat Chatbox: Value = text, Extra = options like send=true notify=false."] = "VRChat 聊天框：值 = 文本，附加 = 例如 send=true notify=false。",
        ["VRChat Typing: Value = true or false."] = "VRChat 正在输入：值 = true 或 false。",
        ["Edit the selected step."] = "编辑当前选中的步骤。"
    };

    public static bool UseSimplifiedChinese()
    {
        var culture = CultureInfo.CurrentUICulture;
        return string.Equals(culture.TwoLetterISOLanguageName, "zh", StringComparison.OrdinalIgnoreCase);
    }

    public static string Translate(string english, string fallback)
    {
        if (SimplifiedChinese.TryGetValue(english, out var translated))
        {
            return translated;
        }

        return LooksCorrupted(fallback) ? english : fallback;
    }

    private static bool LooksCorrupted(string text) => text.Contains('\uFFFD') || text.Contains('\u951F') || text.Count(static ch => ch == '?') >= 3;
}